-- 1. How many products exist in each category?
select cat.cat_name, count(p.prod_id) as prod_count
from products p
LEFT JOIN categories cat ON cat.cat_id = p.cat_id
group by cat_name
order by prod_count desc;

-- 	2. What is the average price of products by category?
select cat.cat_name, avg(price) as avg_price
from products p
LEFT JOIN categories cat ON cat.cat_id = p.cat_id
group by cat_name;

-- 3. Which products have the highest total sales volume (by quantity)?
select p.prod_id, p.prod_name, sum(ord.quantity) as total_sales_volume
from order_details ord
JOIN products p ON p.prod_id = ord.prod_id
group by p.prod_id, p.prod_name
order by total_sales_volume desc
limit 5;

-- 4. What is the total revenue generated by each product?
select p.prod_id, p.prod_name, sum(ord.total_price) as total_revenue
from order_details ord
JOIN products p ON p.prod_id = ord.prod_id
group by p.prod_id, p.prod_name
order by total_revenue desc;

-- 5. How do product sales vary by category and supplier?
select cat.cat_name, s.sup_name,
    sum(ord.quantity) as total_units_sold,
    sum(ord.total_price) as total_revenue
from order_details ord
JOIN products p ON p.prod_id = ord.prod_id
JOIN categories cat ON cat.cat_id = p.cat_id
JOIN supplier s ON s.sup_id = p.sup_id
group by cat.cat_name, s.sup_name
order by total_revenue desc;